const FALLBACK_SUPABASE_URL = "https://heekxcsmltfpwrjdbbcg.supabase.co";
const FALLBACK_SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZWt4Y3NtbHRmcHdyamRiYmNnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1OTU5MzMsImV4cCI6MjA5MjE3MTkzM30.2af8g4S89tZjEvxp1QN791cZ_ZoMpcGuMrZVBKRSAlw";

export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? FALLBACK_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? FALLBACK_SUPABASE_PUBLISHABLE_KEY;
